name: Daily Sheet Snapshot to Telegram

on:
  schedule:
    - cron: '0 2 * * *'  # 9h sáng Việt Nam (UTC+7)
  workflow_dispatch:     # Cho phép chạy thủ công

jobs:
  send_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
        run: |
          python send_image.py
